Add Battlefield V
PresenceDB/activity-customization pull request #27
Opened 2021-08-03 13:09 UTC by 124-Darky

2021-08-03 20:48 UTC, MuteBefehl requested changes

2021-08-03 20:48 UTC, MuteBefehl commented on customizations/Battlefield™ V.json
> +    "imageUrl": "https://i.imgur.com/9NJho2u.jpg",
Please use an image without text.
Also, the color does not fit.

2021-08-03 20:51 UTC, vascYT commented on customizations/Battlefield™ V.json
> +    "color": "#0384fc",
Please use a different color

2021-08-03 20:52 UTC, vascYT commented on customizations/Battlefield™ V.json
> +    "imageUrl": "https://i.imgur.com/9NJho2u.jpg",
Also use an image without text.

2021-08-06 17:32 UTC, MuteBefehl commented
As privately agreed, I close this pr because the requested changes were not made.

2021-08-06 17:32 UTC, closed without merging